# Generated by Django 4.2 on 2023-06-13 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accepter_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1.'), django.core.validators.MaxValueValidator(5, message='Rating cannot exceed 5.')]),
        ),
        migrations.AddField(
            model_name='request',
            name='requester_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1.'), django.core.validators.MaxValueValidator(5, message='Rating cannot exceed 5.')]),
        ),
    ]
